# Generated by Django 6.0.6 on 2026-06-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_remove_training_exercises_exercise_rest_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="exercises",
            field=models.ManyToManyField(
                through="authentication.TrainingExercise", to="authentication.exercise"
            ),
        ),
    ]
