# Generated by Django 6.0.6 on 2026-07-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_training_exercises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
